### ISSUE TITLE
Please help 🙏

### ISSUE THREAD

**Issue by teresakl18** [tbhaxor/whatabomb#12]
$ python bomb.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/whatabomb/bomb.py", line 1, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

Can you say what to do on this

Plzz help to resolve this

**Comment by tbhaxor** [comment]
Execute `pip install -r requirements.txt`
