### ISSUE TITLE
Not working in windows!

### ISSUE THREAD

**Issue by amustaque97** [tbhaxor/whatabomb#2]
When i press the bomb button suddenly message pops ' Python stopped working'. I guess this might be the path issue.

![untitled](https://user-images.githubusercontent.com/21127788/42651751-f36dbba4-862d-11e8-8b96-f9e903a20796.png)

**Comment by tbhaxor** [comment]
Its a PATH variable not set error
Make sure you have [ChromeWebDriver](chromedriver.chromium.org/downloads) added to your path

**Comment by amustaque97** [comment]
and can u tell how can i configure it?

**Comment by tbhaxor** [comment]
watch [this](https://www.youtube.com/watch?v=bEroNNzqlF4) video
