### ISSUE TITLE
how to add ChromeWebDriver path in kali linux with chrome

### ISSUE THREAD

**Issue by vishalsangwa** [tbhaxor/whatabomb#3]
hey friends can anybody help me out !!!

i installed the required Dependencies 
 as u said for  for Automatic Install
$ pip install -r requirements.txt
this didnt work bcoz you need to install pyqt5 for python3, not python 2.

So i tried  with
$apt install python3-pyqt5
then i did
$ pip install selenium 
and all goes well

and it worked and rest all work but i am not getting how to add ChromeWebDriver path in kali linux with chrome.

can anyone help me out and explain the step by step process.!!!!

**Comment by tbhaxor** [comment]
@vishasangwa  copy the driver file to any one of the following location
1. /usr/bin/ 
2. /usr/$USER/.local/bin
3. /bin
