### ISSUE TITLE
error syntax

### ISSUE THREAD

**Issue by sebk95** [tbhaxor/whatabomb#5]
terminal ─╼ $python bomb.py
  File "bomb.py", line 164
    print("sent {} messages".format(i + 1), end="\r")
                                               ^
SyntaxError: invalid syntax

**Comment by tbhaxor** [comment]
![image](https://user-images.githubusercontent.com/28386721/60384028-cdcc4900-9a96-11e9-956d-f1d6e8c8f245.png)
It's working here

I am closing this feel free to reopen
