### ISSUE TITLE
Python3 crashes (macOS)

### ISSUE THREAD

**Issue by 0n1cOn3** [tbhaxor/whatabomb#8]
2019-11-03 06:38:05.892 Python[92645:1587823] -[QNSApplication _setup:]: unrecognized selector sent to instance 0x7fbf96e52e40
2019-11-03 06:38:05.894 Python[92645:1587823] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[QNSApplication _setup:]: unrecognized selector sent to instance 0x7fbf96e52e40'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2e710783 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff645238f3 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2e79aed5 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff2e6b6d60 ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff2e6b6738 _CF_forwarding_prep_0 + 120
	5   Tk                                  0x00007fff3c091f24 TkpInit + 655
	6   Tk                                  0x00007fff3c011cbb Tk_Init + 1706
	7   _tkinter.cpython-37m-darwin.so      0x0000000107338dd9 Tcl_AppInit + 84
	8   _tkinter.cpython-37m-darwin.so      0x000000010733465f _tkinter_create + 1056
	9   Python                              0x0000000104746448 _PyMethodDef_RawFastCallKeywords + 488
	10  Python                              0x00000001047459d4 _PyCFunction_FastCallKeywords + 41
	11  Python                              0x00000001047da384 call_function + 628
	12  Python                              0x00000001047d335f _PyEval_EvalFrameDefault + 6767
	13  Python                              0x00000001047dabe5 _PyEval_EvalCodeWithName + 1698
	14  Python                              0x0000000104745614 _PyFunction_FastCallDict + 444
	15  Python                              0x000000010474671b _PyObject_Call_Prepend + 131
	16  Python                              0x0000000104783ade slot_tp_init + 80
	17  Python                              0x000000010478080a type_call + 172
	18  Python                              0x000000010474584a _PyObject_FastCallKeywords + 358
	19  Python                              0x00000001047da3ea call_function + 730
	20  Python                              0x00000001047d33fa _PyEval_EvalFrameDefault + 6922
	21  Python                              0x0000000104745da8 function_code_fastcall + 106
	22  Python                              0x00000001047da3f1 call_function + 737
	23  Python                              0x00000001047d3346 _PyEval_EvalFrameDefault + 6742
	24  Python                              0x00000001047dabe5 _PyEval_EvalCodeWithName + 1698
	25  Python                              0x00000001047d184d PyEval_EvalCode + 51
	26  Python                              0x00000001047ffc64 run_mod + 54
	27  Python                              0x00000001047fec97 PyRun_FileExFlags + 160
	28  Python                              0x00000001047fe34e PyRun_SimpleFileExFlags + 270
	29  Python                              0x0000000104816b66 pymain_main + 5445
	30  Python                              0x00000001048171d4 _Py_UnixMain + 56
	31  libdyld.dylib                       0x00007fff65876405 start + 1
	32  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
./collection.sh: line 16: 92645 Abort trap: 6           python3 bomb.py

**Comment by tbhaxor** [comment]
Have you installed the latest version of chromedriver?

**Comment by tbhaxor** [comment]
Due to inactivity, i am closing this issue. If the issue still persists, feel free to reopen the same or create a new one

**Comment by maxsptz** [comment]
i get the same error. chrome driver is updated to 80.something

**Comment by tbhaxor** [comment]
Could you share the screenshot? And have u tried the [binary](https://github.com/tbhaxor/whatabomb/tree/master/bin)

**Comment by maxsptz** [comment]
![screenshot](https://user-images.githubusercontent.com/47332301/76334839-f2e6ac00-62f3-11ea-8fba-939628f0c264.png)

Hello, i have not tried the binary, as im on macOS im not sure how to execute that file.

**Comment by maxsptz** [comment]
could you explain how to use the binary?
Thanks.

**Comment by tbhaxor** [comment]
have u installed the pip [requirements](https://github.com/tbhaxor/whatabomb/blob/master/requirements.txt)?

see the instructions -> https://github.com/tbhaxor/whatabomb#dependencies

**Comment by maxsptz** [comment]
![Here is proof](https://user-images.githubusercontent.com/47332301/76341371-3c87c480-62fd-11ea-887f-6ea727c2a843.png)
here is proof that i have installed them all.

**Comment by tbhaxor** [comment]
This is not the programming issue then. I would like you to create the question for the same on stackoverflow

**Comment by maxsptz** [comment]
I looked around for a bit, and it seems like there is an error with a button press, and thats why it doesnt work. It seems like this is related to the code still
Does it work for you on macOS? Have you tested it yourself? 
Regards
[Stackoverflow#1](https://stackoverflow.com/questions/30358877/nsinvalidargumentexception-reason-unrecognized-selector-sent-to-instance)
[Stackoverflow#2](https://stackoverflow.com/questions/2455161/unrecognized-selector-sent-to-instance-error-in-objective-c)

**Comment by tbhaxor** [comment]
Maybe this could the error of PyQT5.

This application is tested only on Linux and Windows.
