### ISSUE TITLE
ChromeDriver is assuming that Chromehas crashed.

### ISSUE THREAD

**Issue by Fabxx** [tbhaxor/whatabomb#9]
Traceback (most recent call last):
  File "bomb.py", line 112, in bomb
    driver = webdriver.Chrome()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 95, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Aborted

Kali Linux 2020.x

**Comment by Fabxx** [comment]
Updated.

**Comment by tbhaxor** [comment]
Is it working?

**Comment by tbhaxor** [comment]
Have you read this article? https://chromedriver.chromium.org/help/chrome-doesn-t-start
Could you provide me the versions of the following
+ Python
+ Selenium
+ Chromedriver
+ ChromeBrowser

**Comment by Fabxx** [comment]
@tbhaxor  I think the problem might be related about the fact that chrome can't be launched with --no-sandbox since i'm as root. So i need to add options to chrome to let it start with the necessary flags. How do i add the flags to the chrome.exe so it won't crash anymore?

**Comment by tbhaxor** [comment]
@FabxBs There are plenty of answers on google about running chrome as root
+ https://unix.stackexchange.com/a/175969/391522
+ https://stackoverflow.com/a/54434098/10362396

Since this application purely build on the normal user, I ask you to give it a try at normal user privileges. For now I am closing this, as it's not part of this project. If you get errors, reopen it anytime

**Comment by Fabxx** [comment]
I fixed with a guide that was adding the --no-sandbox flags in the chrome script, thanks for your help. By the way while opening the window in chrome, there's no page displayed or QR code, just a blank page. with this error code: 
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
Aborted

**Comment by tbhaxor** [comment]
If you would provide a screenshot, it will be helpful in debugging

**Comment by Fabxx** [comment]
![image](https://user-images.githubusercontent.com/30447649/80625422-777cbd80-8a4d-11ea-9834-7fd91fff12f1.png)
the page remains like this, if i close it, i get that error mentioned before.

**Comment by tbhaxor** [comment]
Make sure you are giving sufficient memory to the VM

**Comment by Fabxx** [comment]
8GB of RAM should be enough afaik, and 520gb to the HDD
